version: "3.7"

services:
  store-management:
    depends_on:
      - mysql
    restart: on-failure
    image: sm:jenkins-built
    ports:
      - 8088:8088
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/storeman?createDatabaseIfNotExist=true
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data-compose:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

volumes:
  mysql-data-compose:
